# Generated by Django 3.2.5 on 2021-08-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcourse',
            name='student_numbers',
            field=models.IntegerField(null=True),
        ),
    ]
