# Generated by Django 3.2.5 on 2021-08-18 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210818_2046'),
        ('training', '0003_auto_20210818_2117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TProvider',
            new_name='TrainingProvider',
        ),
    ]
