# Generated by Django 3.2.5 on 2021-08-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_rename_tprovider_trainingprovider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='course_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='available',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
