# Generated by Django 3.2.5 on 2021-08-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_auto_20210819_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_student_numbers',
            field=models.IntegerField(null=True),
        ),
    ]
