# Generated by Django 3.2.5 on 2021-08-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_course_max_student_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='max_student_numbers',
            field=models.IntegerField(default=100, null=True),
        ),
    ]
