# Generated by Django 3.2.5 on 2021-08-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_alter_course_max_student_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student_numbers',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
