# Generated by Django 3.2.5 on 2021-08-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_alter_course_student_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='max_student_numbers',
        ),
        migrations.RemoveField(
            model_name='course',
            name='student_numbers',
        ),
        migrations.AddField(
            model_name='usercourse',
            name='max_student_numbers',
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='student_numbers',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
