# Generated by Django 3.2.5 on 2021-08-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_auto_20210819_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='max_student_numbers',
        ),
        migrations.AddField(
            model_name='course',
            name='max_student_numbers',
            field=models.IntegerField(default=100, null=True),
        ),
    ]
