# Generated by Django 3.2.5 on 2021-08-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_auto_20210819_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='student_numbers',
        ),
        migrations.AddField(
            model_name='course',
            name='student_numbers',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
