# Generated by Django 3.2.5 on 2021-08-19 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_alter_usercourse_course_pass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student_numbers',
        ),
    ]
