# Generated by Django 3.2.5 on 2021-08-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_remove_course_student_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='enrolled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
