# Generated by Django 3.2.5 on 2021-08-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_family_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count_trainings',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
